# Generated by Django 3.2.7 on 2021-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationimage',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate_type',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Moderate', 'Moderate'), ('Rainy', 'Rainy')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='famous_for',
            field=models.CharField(blank=True, choices=[('Scenery', 'Scenery'), ('Food', 'Food'), ('Weather', 'Weather'), ('Night Life', 'Night Life')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='terrain_type',
            field=models.CharField(blank=True, choices=[('Plain', 'Plain'), ('Mountain', 'Mountain'), ('Desert', 'Desert'), ('Forest', 'Forest'), ('Glacier', 'Glacier'), ('Valley', 'Valley'), ('Ocean', 'Ocean')], max_length=32, null=True),
        ),
    ]
