# Generated by Django 3.2.7 on 2021-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211004_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='famous_for',
            field=models.CharField(blank=True, choices=[('Scenery', 'Scenery'), ('Wildlife', 'Wildlife'), ('Food', 'Food'), ('Weather', 'Weather'), ('Night Life', 'Night Life'), ('Monuments', 'Monuments')], max_length=64, null=True),
        ),
    ]
