# Generated by Django 3.2.7 on 2021-10-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_wish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deal',
            new_name='Package',
        ),
    ]
