# Generated by Django 3.2.7 on 2021-10-04 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 4, 20, 35, 25, 450122, tzinfo=utc), null=True),
        ),
    ]
